'use strict';

const {
  default: makeWASocket,
    fetchLatestBaileysVersion,
      DisconnectReason,
        makeCacheableSignalKeyStore,h
        } = require('@whiskeysockets/baileys');
        const pino = require('pino');

        let SocksProxyAgent, HttpsProxyAgent;
        try {
          SocksProxyAgent = require('socks-proxy-agent').SocksProxyAgent;
            HttpsProxyAgent = require('https-proxy-agent').HttpsProxyAgent;
            } catch (e) {
              console.warn('[SM] Proxy modules not available:', e.message);
              }

              const multiStore = require('./multi-store');

              const sessions = new Map();

              let _globalSse = null;
              function setSseManager(sse) { _globalSse = sse; }

              let _supabase = null;
              function init(supabase) {
                _supabase = supabase;
                  multiStore.init(supabase);
                  }

                  function agentFor(storeId) {
                    const url = (multiStore.getProxyUrlForStore && multiStore.getProxyUrlForStore(storeId))
                        || process.env.WA_PROXY_URL;
                          if (!url) return undefined;
                            try {
                                return url.startsWith('socks')
                                      ? new SocksProxyAgent(url)
                                            : new HttpsProxyAgent(url);
                                              } catch (e) {
                                                  console.error('[SM] Error creating agent for', storeId.substring(0, 8), e.message);
                                                      return undefined;
                                                        }
                                                        }

                                                        async function authFor(storeId) {
                                                          if (typeof multiStore.makeAuthState !== 'function') {
                                                              throw new Error('[SM] multiStore.makeAuthState not implemented');
                                                                }
                                                                  return multiStore.makeAuthState(storeId);
                                                                  }

                                                                  function broadcastForStore(storeId, payload) {
                                                                    if (!_globalSse) return;
                                                                      try {
                                                                          _globalSse.broadcast({ ...payload, store_id: storeId });
                                                                            } catch (e) {}
                                                                            }

                                                                            const BROWSERS = [
                                                                              ['Chrome (Windows)', 'Chrome', '148.0.3967.83'],
                                                                                ['Chrome (Windows)', 'Chrome', '149.0.7827.22'],
                                                                                  ['Chrome (Mac OS)',  'Chrome', '148.0.3967.83'],
                                                                                    ['Edge (Windows)',   'Edge',   '148.0.3967.83'],
                                                                                      ['Chrome (Linux)',   'Chrome', '148.0.3967.75'],
                                                                                      ];

                                                                                      async function startSession(storeId) {
                                                                                        let s = sessions.get(storeId);
                                                                                          if (!s) {
                                                                                              s = { storeId, sock: null, status: 'connecting', qr: null,
                                                                                                        startedAt: Date.now(), _reconnTimer: null };
                                                                                                            sessions.set(storeId, s);
                                                                                                              } else {
                                                                                                                  _cleanupSock(s);
                                                                                                                      s.status = 'connecting';
                                                                                                                          s.qr = null;
                                                                                                                            }
                                                                                                                            
                                                                                                                              broadcastForStore(storeId, { type: 'connection', data: { status: 'connecting' } });
                                                                                                                                console.log('[SM][' + storeId.substring(0, 8) + '] startSession');
                                                                                                                                
                                                                                                                                  let state, saveCreds;
                                                                                                                                    try {
                                                                                                                                        ({ state, saveCreds } = await authFor(storeId));
                                                                                                                                          } catch (e) {
                                                                                                                                              console.error('[SM][' + storeId.substring(0, 8) + '] authFor error:', e.message);
                                                                                                                                                  s.status = 'connecting';
                                                                                                                                                      _scheduleReconnect(s, 5000);
                                                                                                                                                          return s;
                                                                                                                                                            }
                                                                                                                                                            
                                                                                                                                                              const agent  = agentFor(storeId);
                                                                                                                                                                const logger = pino({ level: 'silent' });
                                                                                                                                                                
                                                                                                                                                                  let version;
                                                                                                                                                                    try {
                                                                                                                                                                        ({ version } = await fetchLatestBaileysVersion());
                                                                                                                                                                          } catch (e) {
                                                                                                                                                                              version = [2, 3000, 1023251599];
                                                                                                                                                                                }
                                                                                                                                                                                
                                                                                                                                                                                  let browser;
                                                                                                                                                                                    if (state.creds && state.creds._smBrowserFP) {
                                                                                                                                                                                        browser = state.creds._smBrowserFP;
                                                                                                                                                                                          } else {
                                                                                                                                                                                              browser = BROWSERS[Math.floor(Math.random() * BROWSERS.length)];
                                                                                                                                                                                                  if (state.creds) {
                                                                                                                                                                                                        state.creds._smBrowserFP = browser;
                                                                                                                                                                                                              saveCreds().catch(() => {});
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    
                                                                                                                                                                                                                      const sock = makeWASocket({
                                                                                                                                                                                                                          version,
                                                                                                                                                                                                                              logger,
                                                                                                                                                                                                                                  auth: {
                                                                                                                                                                                                                                        creds: state.creds,
                                                                                                                                                                                                                                              keys: makeCacheableSignalKeyStore(state.keys, logger),
                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                      browser,
                                                                                                                                                                                                                                                          agent,
                                                                                                                                                                                                                                                              fetchAgent: agent,
                                                                                                                                                                                                                                                                  markOnlineOnConnect: false,
                                                                                                                                                                                                                                                                      printQRInTerminal: false,
                                                                                                                                                                                                                                                                          generateHighQualityLinkPreview: false,
                                                                                                                                                                                                                                                                              syncFullHistory: false,
                                                                                                                                                                                                                                                                                  connectTimeoutMs: 15000,
                                                                                                                                                                                                                          keepAliveIntervalMs: 15000,
                                                                                                                                                                                                                                                                                      retryRequestDelayMs: 250,
                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                          s.sock = sock;
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            sock.ev.on('creds.update', saveCreds);
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                              sock.ev.on('connection.update', async (update) => {
                                                                                                                                                                                                                                                                                                  const { connection, lastDisconnect, qr } = update;
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                      if (qr) {
                                                                                                                                                                                                                                                                                                            s.qr     = qr;
                                                                                                                                                                                                                                                                                                                  s.status = 'qr';
                                                                                                                                                                                                                                                                                                                        console.log('[SM][' + storeId.substring(0, 8) + '] QR ready');
                                                                                                                                                                                                                                                                                                                              broadcastForStore(storeId, { type: 'qr', data: qr });
                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      if (connection === 'open') {
                                                                                                                                                                                                                                                                                                                                            s.status = 'connected';
                                                                                                                                                                                                                                                                                                                                                  s.qr     = null;
                                                                                                                                                                                                                                                                                                                                                        console.log('[SM][' + storeId.substring(0, 8) + '] CONNECTED as', sock.user?.id || '?');
                                                                                                                                                                                                                                                                                                                                                              broadcastForStore(storeId, { type: 'connection', data: { status: 'connected' } });
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                      if (connection === 'close') {
                                                                                                                                                                                                                                                                                                                                                                            s.status = 'reconnecting';
                                                                                                                                                                                                                                                                                                                                                                                  s.qr     = null;
                                                                                                                                                                                                                                                                                                                                                                                        const code = lastDisconnect?.error?.output?.statusCode;
                                                                                                                                                                                                                                                                                                                                                                                              console.log('[SM][' + storeId.substring(0, 8) + '] Disconnected reason=' + code);
                                                                                                                                                                                                                                                                                                                                                                                                    broadcastForStore(storeId, { type: 'connection', data: { status: 'disconnected', reason: code } });
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                          if (code === DisconnectReason.loggedOut) {
                                                                                                                                                                                                                                                                                                                                                                                                                  s.status = 'logged_out';
                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('[SM][' + storeId.substring(0, 8) + '] loggedOut — clearing auth');
                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (_supabase) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        await _supabase.from('oasis_wa_auth').delete().eq('store_id', storeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  broadcastForStore(storeId, { type: 'connection', data: { status: 'logged_out' } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      _scheduleReconnect(s, 1500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              async function getOrCreate(storeId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const existing = sessions.get(storeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (existing && existing.sock) return existing;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return startSession(storeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function get(storeId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return sessions.get(storeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function listAll() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return Array.from(sessions.values()).map(s => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            storeId:        s.storeId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status:         s.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    hasQR:          !!s.qr,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        connectedPhone: s.sock?.user?.id || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            startedAt:      s.startedAt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              async function stopSession(storeId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const s = sessions.get(storeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!s) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _cleanupSock(s);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sessions.delete(storeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log('[SM][' + storeId.substring(0, 8) + '] Session stopped');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function _cleanupSock(s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (s._reconnTimer) { clearTimeout(s._reconnTimer); s._reconnTimer = null; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (s.sock) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try { s.sock.ev.removeAllListeners(); } catch (e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try { s.sock.end(undefined); }          catch (e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        s.sock = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function _scheduleReconnect(s, delayMs) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (s._reconnTimer) clearTimeout(s._reconnTimer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              s._reconnTimer = setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  s._reconnTimer = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('[SM][' + s.storeId.substring(0, 8) + '] Reconnecting...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          startSession(s.storeId).catch(e =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('[SM] Reconnect error:', e.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, delayMs);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      module.exports = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        init,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setSseManager,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            startSession,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              getOrCreate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                get,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  listAll,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stopSession,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sessions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
